-- =========================================================================
-- SCRIPT DE CONFIGURAÇÃO DA TABELA NO SUPABASE
-- Execute este script no SQL Editor do seu painel do Supabase.
-- Ele recria a tabela 'votos' com as colunas necessárias e configura 
-- as políticas de segurança (RLS) para permitir inserções e leituras gratuitas.
-- =========================================================================

-- 1. Remover a tabela antiga se já existir para garantir a estrutura correta de colunas
DROP TABLE IF EXISTS public.votos CASCADE;

-- 2. Criar a nova tabela 'votos' com todas as colunas corretas
CREATE TABLE public.votos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  player_id text NOT NULL,
  voter_id text NOT NULL,
  date_str text NOT NULL,
  voter_name text DEFAULT 'Anônimo'::text,
  voter_email text,
  voter_phone text,
  ip_address text,
  location_info text,
  user_agent text
);

-- 3. Habilitar segurança em nível de linha (RLS)
ALTER TABLE public.votos ENABLE ROW LEVEL SECURITY;

-- 4. Excluir políticas antigas se existirem para evitar conflitos
DROP POLICY IF EXISTS "Permitir inserções públicas de votos" ON public.votos;
DROP POLICY IF EXISTS "Permitir leitura pública de votos" ON public.votos;
DROP POLICY IF EXISTS "Permitir exclusão pública de votos" ON public.votos;

-- 5. Criar políticas para permitir acesso público de escrita, leitura e exclusão usando a chave anon
CREATE POLICY "Permitir inserções públicas de votos" 
ON public.votos 
FOR INSERT 
TO anon 
WITH CHECK (true);

CREATE POLICY "Permitir leitura pública de votos" 
ON public.votos 
FOR SELECT 
TO anon 
USING (true);

CREATE POLICY "Permitir exclusão pública de votos" 
ON public.votos 
FOR DELETE 
TO anon 
USING (true);

-- 6. Adicionar índices para otimizar a velocidade de busca e contagem de votos
CREATE INDEX IF NOT EXISTS votos_player_id_idx ON public.votos (player_id);
CREATE INDEX IF NOT EXISTS votos_voter_id_date_str_idx ON public.votos (voter_id, date_str);

