-- =========================================================================
-- SCRIPT COMPLETO DE CONFIGURAÇÃO DE TABELAS E SEGURANÇA NO SUPABASE
-- =========================================================================
-- Execute este script completo no SQL Editor do seu painel do Supabase.
-- Ele cria e configura as tabelas 'votos', 'jogadores' e 'configuracoes'
-- com as políticas de acesso público (RLS) corretas para que o seu site
-- estático (Netlify) consiga salvar e ler dados diretamente.
-- =========================================================================

-- -------------------------------------------------------------------------
-- 1. CONFIGURAÇÃO DA TABELA DE JOGADORES (jogadores)
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.jogadores (
  id text PRIMARY KEY,
  nome text NOT NULL,
  time text NOT NULL,
  logo_url text DEFAULT ''::text,
  criado_em timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS ou Desabilitar para evitar erros (Se quiser total facilidade, desative com: ALTER TABLE public.jogadores DISABLE ROW LEVEL SECURITY;)
ALTER TABLE public.jogadores ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Permitir leitura pública de jogadores" ON public.jogadores;
DROP POLICY IF EXISTS "Permitir inserções públicas de jogadores" ON public.jogadores;
DROP POLICY IF EXISTS "Permitir atualização pública de jogadores" ON public.jogadores;
DROP POLICY IF EXISTS "Permitir exclusão pública de jogadores" ON public.jogadores;

CREATE POLICY "Permitir leitura pública de jogadores" ON public.jogadores FOR SELECT TO anon USING (true);
CREATE POLICY "Permitir inserções públicas de jogadores" ON public.jogadores FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Permitir atualização pública de jogadores" ON public.jogadores FOR UPDATE TO anon USING (true) WITH CHECK (true);
CREATE POLICY "Permitir exclusão pública de jogadores" ON public.jogadores FOR DELETE TO anon USING (true);

-- -------------------------------------------------------------------------
-- 2. CONFIGURAÇÃO DA TABELA DE CONFIGURAÇÕES DO SISTEMA (configuracoes)
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.configuracoes (
  id text PRIMARY KEY,
  dados text NOT NULL,
  criado_em timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS
ALTER TABLE public.configuracoes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Permitir leitura pública de configuracoes" ON public.configuracoes;
DROP POLICY IF EXISTS "Permitir inserções públicas de configuracoes" ON public.configuracoes;
DROP POLICY IF EXISTS "Permitir atualização pública de configuracoes" ON public.configuracoes;

CREATE POLICY "Permitir leitura pública de configuracoes" ON public.configuracoes FOR SELECT TO anon USING (true);
CREATE POLICY "Permitir inserções públicas de configuracoes" ON public.configuracoes FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Permitir atualização pública de configuracoes" ON public.configuracoes FOR UPDATE TO anon USING (true) WITH CHECK (true);

-- -------------------------------------------------------------------------
-- 3. CONFIGURAÇÃO DA TABELA DE VOTOS (votos)
-- -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.votos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  player_id text NOT NULL,
  voter_id text NOT NULL,
  date_str text NOT NULL,
  voter_name text DEFAULT 'Anônimo'::text,
  voter_email text,
  voter_phone text,
  ip_address text,
  location_info text,
  user_agent text
);

-- Habilitar RLS
ALTER TABLE public.votos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Permitir inserções públicas de votos" ON public.votos;
DROP POLICY IF EXISTS "Permitir leitura pública de votos" ON public.votos;
DROP POLICY IF EXISTS "Permitir exclusão pública de votos" ON public.votos;

CREATE POLICY "Permitir inserções públicas de votos" ON public.votos FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "Permitir leitura pública de votos" ON public.votos FOR SELECT TO anon USING (true);
CREATE POLICY "Permitir exclusão pública de votos" ON public.votos FOR DELETE TO anon USING (true);

-- Índices adicionais para otimizar a velocidade de contagem de votos
CREATE INDEX IF NOT EXISTS votos_player_id_idx ON public.votos (player_id);
CREATE INDEX IF NOT EXISTS votos_voter_id_date_str_idx ON public.votos (voter_id, date_str);

-- -------------------------------------------------------------------------
-- OPÇÃO ULTRA-SIMPLES E À PROVA DE ERROS:
-- Se você continuar tendo erros de RLS ou políticas, execute a linha abaixo:
-- -------------------------------------------------------------------------
-- ALTER TABLE public.jogadores DISABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.configuracoes DISABLE ROW LEVEL SECURITY;
-- ALTER TABLE public.votos DISABLE ROW LEVEL SECURITY;
